name: cicd
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TUNNEL_SERVICE_HOSTNAME: ${{ secrets.TUNNEL_SERVICE_HOSTNAME }}
  TUNNEL_SERVICE_TOKEN_ID: ${{ secrets.TUNNEL_SERVICE_TOKEN_ID }}
  TUNNEL_SERVICE_TOKEN_SECRET: ${{ secrets.TUNNEL_SERVICE_TOKEN_SECRET }}
  SSH_REPO: ${{  secrets.SSH_REPO }}
  SSH_PROXY_COMMAND: "/tmp/cloudflared access ssh"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.3
      - name: Run Test
        run: go test ./...
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Install cloudflared
      run: |
          curl -sL -o /tmp/cloudflared https://github.com/cloudflare/cloudflared/releases/download/2024.11.0/cloudflared-linux-amd64
          chmod +x /tmp/cloudflared
    - name: Run deploy
      run: |
          ssh -o StrictHostKeyChecking=no -o ProxyCommand="${SSH_PROXY_COMMAND}" -l ${SSH_USER} ${TUNNEL_SERVICE_HOSTNAME} "cd ${SSH_REPO} && git pull && docker stop message-expander && docker build ./ -t message-expander && docker run message-expander"

