name: cicd
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SSH_REPO: ${{  secrets.SSH_REPO }}
  SSH_PROXY_COMMAND: "/tmp/cloudflared access ssh --id ${{ secrets.CLOUDFLARE_CLIENT_ID}} --secret ${{ secrets.CLOUDFLARE_CLIENT_SECRET }} --hostname ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.3
      - name: Run Test
        run: go test ./...
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Install cloudflared
      run: |
          curl -sL -o /tmp/cloudflared https://github.com/cloudflare/cloudflared/releases/download/2024.11.0/cloudflared-linux-amd64
          chmod +x /tmp/cloudflared
    - name: Run deploy
      run: |
          ssh -o StrictHostKeyChecking=no ProxyCommand="${SSH_PROXY_COMMAND}" "cd ${SSH_REPO} && git pull && docker stop message-expander && docker build ./ -t message-expander && docker run message-expander"

